/* Tipagem fraca - significa como a linguagem vai lidar com os tipos dos dados = Ex quando declarar 
uma constante mostrar que tipo de variavel é aquela constante - tipo Float,int, string
porem em javascript não acontece isso, pois é uma variavel fracamente tipada */

let qualquer = 'legal'
console.log(qualquer);
console.log(typeof qualquer);

qualquer = 3.2516
console.log(qualquer)
console.log(typeof qualquer)