// String denomina uma cadeia de caracteres

const escola = "estudo"

console.log(escola.charAt(2)); // charAt comando para mostrar a letra de acordo com o numero pedido
console.log(escola.charAt(4));

console.log(escola.charAt(3));
console.log(escola.charAt(1));

console.log(escola.substring(3)) //substring comando para mostrar o resultado da constante a partir do numero pedido em diante
console.log(escola.substring(1, 3)) // mostra apenas as letras correspondente ao numero pedido

console.log('Escola '.concat(escola).concat("!")) // contat serve para concatenar palavras

